site_name: Configurações
site_description: Instruções de configuração de de sistemas, serviços, aplicações, etc.
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
docs_dir: 'mds'
pages:
    - Configurações: index.md
    - Sistemas Operacionais:
        - Arch Linux: 'sistema-operacional/arch-linux.md'
    - Shell:
        - oh-my-zsh: 'shell/oh-my-zsh.md'
    - Git:
        - Git: 'git/git.md'
#    - Servidores Web:
#        - Apache2: 'servidores-web/apache.md'
#    - PHP:
#        - PHP: 'php/php.md'
    - Python:
        - virtualenv: 'python/virtualenv.md'
        - Mkdocs: 'python/mkdocs.md'
    - Node.JS:
        - Node.JS: 'nodejs/nodejs.md'
    - Banco de Dados:
#        - MySQL: 'banco-de-dados/mysql.md'
        - MongoDB: 'banco-de-dados/mongodb.md'
theme: readthedocs
extra:
  version: 1.0
markdown_extensions:
    - smarty
    - nl2br
    - admonition
    - codehilite
    - sane_lists
    - toc:
        permalink: True
        separator: "_"