site_name: Configurações
site_description: Instruções de configuração de de sistemas, serviços, aplicações, etc.
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
docs_dir: 'mds'
pages:
    - Configurações: index.md
    - Sistemas Operacionais:
        - Arch Linux: 'sistema-operacional/arch-linux.md'
    - Git: 'git.md'
    - Python - virtualenv: 'python-virtualenv.md'
    - Mkdocs: 'mkdocs.md'
    #- Servidores Web:
        #- Apache2: 'sistema-operacional/apache.md'
    #- Banco de Dados - SGDB
        #- MySQL: 'sistema-operacional/mysql.md'
    #- PHP: 'php.md'
theme: readthedocs
extra:
    version: 1.0
markdown_extensions:
    - smarty
    - nl2br
    - admonition
    - codehilite
    - sane_lists
    - toc:
        permalink: True
        separator: "_"
